// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ShoppingcartTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void shoppingcart() {
    driver.get("http://localhost:5041/");
    driver.manage().window().setSize(new Dimension(1024, 728));
    driver.findElement(By.linkText("Privacy")).click();
    driver.findElement(By.linkText("Flowers")).click();
    driver.findElement(By.linkText("Add to Cart")).click();
    driver.findElement(By.id("Quantity")).sendKeys("1");
    driver.findElement(By.id("Quantity")).click();
    driver.findElement(By.id("Quantity")).sendKeys("2");
    driver.findElement(By.id("Quantity")).click();
    {
      WebElement element = driver.findElement(By.id("Quantity"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("Quantity")).sendKeys("3");
    driver.findElement(By.id("Quantity")).click();
    driver.findElement(By.id("Quantity")).sendKeys("4");
    driver.findElement(By.id("Quantity")).click();
    driver.findElement(By.cssSelector("form")).click();
    driver.findElement(By.name("addtocart")).click();
    driver.findElement(By.linkText("Flowers")).click();
    driver.findElement(By.cssSelector("tr:nth-child(4) a")).click();
    driver.findElement(By.cssSelector("tr:nth-child(3)")).click();
    driver.findElement(By.id("Quantity")).sendKeys("500");
    driver.findElement(By.name("addtocart")).click();
    driver.findElement(By.linkText("Flowers")).click();
    driver.findElement(By.cssSelector("tr:nth-child(3) a")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("tr:nth-child(3) label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("tr:nth-child(3) label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("tr:nth-child(3) label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("tr:nth-child(3)")).click();
    driver.findElement(By.id("Quantity")).sendKeys("89");
    driver.findElement(By.name("addtocart")).click();
    driver.findElement(By.linkText("Remove")).click();
    driver.findElement(By.cssSelector("tr:nth-child(2) a")).click();
    driver.findElement(By.linkText("Flowers")).click();
    driver.findElement(By.cssSelector("tr:nth-child(4) a")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("tr:nth-child(3) label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("tr:nth-child(3) label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("tr:nth-child(3) label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("tr:nth-child(3)")).click();
    driver.findElement(By.id("Quantity")).sendKeys("4");
    driver.findElement(By.name("addtocart")).click();
  }
}
