// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class ShoppingcartTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void shoppingcart() {
    driver.Navigate().GoToUrl("http://localhost:5041/");
    driver.Manage().Window.Size = new System.Drawing.Size(1024, 728);
    driver.FindElement(By.LinkText("Privacy")).Click();
    driver.FindElement(By.LinkText("Flowers")).Click();
    driver.FindElement(By.LinkText("Add to Cart")).Click();
    driver.FindElement(By.Id("Quantity")).SendKeys("1");
    driver.FindElement(By.Id("Quantity")).Click();
    driver.FindElement(By.Id("Quantity")).SendKeys("2");
    driver.FindElement(By.Id("Quantity")).Click();
    {
      var element = driver.FindElement(By.Id("Quantity"));
      Actions builder = new Actions(driver);
      builder.DoubleClick(element).Perform();
    }
    driver.FindElement(By.Id("Quantity")).SendKeys("3");
    driver.FindElement(By.Id("Quantity")).Click();
    driver.FindElement(By.Id("Quantity")).SendKeys("4");
    driver.FindElement(By.Id("Quantity")).Click();
    driver.FindElement(By.CssSelector("form")).Click();
    driver.FindElement(By.Name("addtocart")).Click();
    driver.FindElement(By.LinkText("Flowers")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(4) a")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(3)")).Click();
    driver.FindElement(By.Id("Quantity")).SendKeys("500");
    driver.FindElement(By.Name("addtocart")).Click();
    driver.FindElement(By.LinkText("Flowers")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(3) a")).Click();
    {
      var element = driver.FindElement(By.CssSelector("tr:nth-child(3) label"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).ClickAndHold().Perform();
    }
    {
      var element = driver.FindElement(By.CssSelector("tr:nth-child(3) label"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.CssSelector("tr:nth-child(3) label"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Release().Perform();
    }
    driver.FindElement(By.CssSelector("tr:nth-child(3)")).Click();
    driver.FindElement(By.Id("Quantity")).SendKeys("89");
    driver.FindElement(By.Name("addtocart")).Click();
    driver.FindElement(By.LinkText("Remove")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(2) a")).Click();
    driver.FindElement(By.LinkText("Flowers")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(4) a")).Click();
    {
      var element = driver.FindElement(By.CssSelector("tr:nth-child(3) label"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).ClickAndHold().Perform();
    }
    {
      var element = driver.FindElement(By.CssSelector("tr:nth-child(3) label"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.CssSelector("tr:nth-child(3) label"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Release().Perform();
    }
    driver.FindElement(By.CssSelector("tr:nth-child(3)")).Click();
    driver.FindElement(By.Id("Quantity")).SendKeys("4");
    driver.FindElement(By.Name("addtocart")).Click();
  }
}
